on:
  release:
    types: [ published ]

jobs:
  publish:
    environment: production
    runs-on: ubuntu-latest
    name: Publish
    steps:
    - run: echo ::set-output name=source_tag::${GITHUB_REF#refs/tags/v}
      name: Get the tag
      id: tag
    - uses: actions/checkout@v2
      name: Check out repository
    - uses: actions/setup-node@v1
      name: Set up Node.js
    - uses: extractions/setup-just@v1
      name: Set up Just
    - run: just release ${{ steps.tag.outputs.source_tag }}
      name: Publish extension ver. ${{ steps.tag.outputs.source_tag }}
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
